questions = [
    {
        "number": 1,
        "question": "Which of the following is true about Bare Metal Solutions?",
        "options": [
            "Enterprise-grade deployment platform",
            "Your existing investment in tooling works as is",
            "Both A and B",
            "None of the above",
        ],
        "correct_answer": 2,
    },
    {
        "number": 2,
        "question": "What is the key feature of Preemptible VMs?",
        "options": [
            "Fixed pricing up to 80% cheaper",
            "Unpredictable billing",
            "Only suitable for long-term workloads",
            "Unavailable for batch processing",
        ],
        "correct_answer": 0,
    },
    {
        "number": 3,
        "question": "Your organization wants to run a container-based application on Google Cloud. Which product should you use for fine-grained traffic and scaling control?",
        "options": [
            "Google Kubernetes Engine",
            "App Engine",
            "Cloud Run",
            "Compute Engine",
        ],
        "correct_answer": 0,
    },
    {
        "number": 4,
        "question": "Which Google Cloud product is designed for transactional SQL queries at scale?",
        "options": ["BigQuery", "Cloud Bigtable", "Cloud Spanner", "Pub/Sub"],
        "correct_answer": 2,
    },
    {
        "number": 5,
        "question": "How does Google Cloud ensure customer data is secure and private at rest?",
        "options": [
            "By aggregating training data for customers",
            "By automatically locking suspicious files",
            "By auditing privacy practices against standards",
            "By providing privacy reviews",
        ],
        "correct_answer": 2,
    },
    {
        "number": 6,
        "question": "Your team needs to build a highly scalable, fully managed application. Which Google Cloud product should you use?",
        "options": [
            "App Engine",
            "Cloud Functions",
            "Google Kubernetes Engine",
            "Bare Metal Solution",
        ],
        "correct_answer": 0,
    },
    {
        "number": 7,
        "question": "What is a Service Level Agreement (SLA)?",
        "options": [
            "A contract guaranteeing a certain level of service, like uptime",
            "A document describing service features",
            "An agreement on pricing for services",
            "A marketing brochure for services",
        ],
        "correct_answer": 0,
    },
    {
        "number": 8,
        "question": "What is the purpose of Cloud Data Loss Prevention (DLP)?",
        "options": [
            "To secure APIs",
            "To encrypt sensitive data",
            "To discover and classify sensitive data",
            "To monitor cloud billing usage",
        ],
        "correct_answer": 2,
    },
    {
        "number": 9,
        "question": "Which Google Cloud product is a serverless compute option?",
        "options": [
            "Cloud Functions",
            "Compute Engine",
            "Cloud Spanner",
            "Cloud Storage",
        ],
        "correct_answer": 0,
    },
    {
        "number": 10,
        "question": "How can organizations minimize cloud expenditures?",
        "options": [
            "Streamline hardware procurement",
            "Share cost views for accountability",
            "Switch from operational to capital expenditure",
            "Tag all cloud resources",
        ],
        "correct_answer": 1,
    },
    {
        "number": 11,
        "question": "What is the benefit of storing data in Cloud Storage Multi-Regional?",
        "options": [
            "Global availability and redundancy",
            "Reduced data retrieval costs",
            "Optimized for archival data",
            "Enhanced real-time processing",
        ],
        "correct_answer": 0,
    },
    {
        "number": 12,
        "question": "What type of storage is most suitable for caching and low-latency workloads?",
        "options": [
            "Persistent Disks",
            "Local SSDs",
            "Cloud Storage",
            "Coldline Storage",
        ],
        "correct_answer": 1,
    },
    {
        "number": 13,
        "question": "An organization wants to leverage serverless architecture for event-driven workloads. Which product should they use?",
        "options": [
            "Cloud Functions",
            "Google Kubernetes Engine",
            "Compute Engine",
            "Bare Metal Solution",
        ],
        "correct_answer": 0,
    },
    {
        "number": 14,
        "question": "What is the advantage of using BigQuery ML?",
        "options": [
            "Allows machine learning using standard SQL",
            "Requires expertise in TensorFlow",
            "Only supports structured data",
            "Limited to batch processing workloads",
        ],
        "correct_answer": 0,
    },
    {
        "number": 15,
        "question": "Which product is suitable for creating and running end-to-end AI models?",
        "options": ["Vertex AI", "BigQuery", "Dataproc", "Cloud Functions"],
        "correct_answer": 0,
    },
    {
        "number": 16,
        "question": "Your organization is running all its workloads in a private cloud on top of a hypervisor. Your organization has decided it wants to move to Google Cloud as quickly as possible. Your organization wants minimal changes to the current environment, while using the maximum amount of managed services Google offers. What should your organization do?",
        "options": [
            "Migrate the workloads to Google Cloud VMware Engine",
            "Migrate the workloads to Compute Engine",
            "Migrate the workloads to Bare Metal Solution",
            "Migrate the workloads to Google Kubernetes Engine",
        ],
        "correct_answer": 0,
    },
    {
        "number": 17,
        "question": "Your company has recently acquired three growing startups in three different countries. You want to reduce overhead in infrastructure management and keep your costs low without sacrificing security and quality of service to your customers. How should you meet these requirements?",
        "options": [
            "Host all your subsidiaries' services on-premises together with your existing services.",
            "Host all your subsidiaries' services together with your existing services on the public cloud.",
            "Build a homogenous infrastructure at each subsidiary, and invest in training their engineers.",
            "Build a homogenous infrastructure at each subsidiary, and invest in hiring more engineers.",
        ],
        "correct_answer": 1,
    },
    {
        "number": 18,
        "question": "Which of the following is/are true about Bare Metal Solutions?",
        "options": [
            "Enterprise-grade deployment platform",
            "All your existing investment in tooling and best practices will work as is",
            "Continue to run any version, and feature set, any database option, and any customizations (patchsets)",
            "All of the Above",
        ],
        "correct_answer": 3,
    },
    {
        "number": 19,
        "question": "An organization wants to dynamically adjust its application to serve different user needs. What are the benefits of storing their data in the cloud for this use case?",
        "options": [
            "Data can be stored in archive for long term access",
            "Automatic data cleaning and validation",
            "Real-time data ingestion and analysis",
            "No data access management required",
        ],
        "correct_answer": 2,
    },
    {
        "number": 20,
        "question": "A retail store has discovered a cost-effective solution for creating self-service kiosks. They can use existing check-out hardware and purchase a virtual customer service application. Why do they also need an API?",
        "options": [
            "To connect the check-out hardware to the public cloud.",
            "To connect the new application with the legacy system.",
            "To migrate all customer data for disaster recovery.",
            "To update the check-out hardware remotely.",
        ],
        "correct_answer": 1,
    },
    {
        "number": 21,
        "question": "Your company security team manages access control to production systems using an LDAP directory group. How is this access control managed in the Google Cloud production project?",
        "options": [
            "Assign the proper role to the Service Account in the project's IAM Policy",
            "Grant each user the roles/iam.serviceAccountUser role on a service account that exists in the Google Group.",
            "Assign the proper role to the Google Group in the project's IAM Policy.",
            "Create the project in a folder with the same name as the LDAP directory group.",
        ],
        "correct_answer": 2,
    },
    {
        "number": 22,
        "question": "A video game organization has invested in cloud technology to generate insights from user behaviors. They want to ensure recommendations of games are aligned to players' interests. What may have prompted this business decision?",
        "options": [
            "Customers expect faster time to market for games.",
            "Employees expect source code changes to be deployed faster.",
            "Customers expect a personalized experience.",
            "Employees expect more predictable data management spending.",
        ],
        "correct_answer": 2,
    },
    {
        "number": 23,
        "question": "Which Google Cloud product is designed to reduce the risks of handling personally identifiable information (PII)?",
        "options": [
            "Cloud Storage",
            "Google Cloud Armor",
            "Cloud Data Loss Prevention",
            "Secret Manager",
        ],
        "correct_answer": 2,
    },
    {
        "number": 24,
        "question": "Which Google Cloud service or feature lets you build machine learning models using Standard SQL and data in a data warehouse?",
        "options": [
            "BigQuery ML",
            "TensorFlow",
            "AutoML Tables",
            "Cloud Bigtable ML",
        ],
        "correct_answer": 0,
    },
    {
        "number": 25,
        "question": "An organization is looking for a storage solution that will help them serve content to users worldwide. They need a solution that offers a high level of availability. What feature of Cloud Storage would they benefit from?",
        "options": [
            "Global metadata",
            "Object versioning",
            "Data encryption",
            "Multi-regional storage",
        ],
        "correct_answer": 3,
    },
    {
        "number": 26,
        "question": "An organization has servers running mission-critical workloads on-premises around the world. They want to modernize their infrastructure with a multi-cloud architecture. What benefit could the organization experience?",
        "options": [
            "Ability to disable regional network connectivity during cyber attacks",
            "Ability to keep backups of their data on-premises in case of failure",
            "Full management access to their regional infrastructure",
            "Reduced likelihood of system failure during high demand events",
        ],
        "correct_answer": 3,
    },
    {
        "number": 27,
        "question": "An organization wants to build autoscaling web applications without having to manage application infrastructure. Which Google Cloud product should they use?",
        "options": ["App Engine", "AutoML", "Anthos", "Apigee"],
        "correct_answer": 0,
    },
    {
        "number": 28,
        "question": "Why is data stored in Google Cloud secure and private?",
        "options": [
            "Data is encrypted by the Security Command Center",
            "Data is encrypted by Cloud Data Loss Prevention",
            "Data is encrypted by default",
            "Data is encrypted when an appropriate tag is applied",
        ],
        "correct_answer": 2,
    },
    {
        "number": 29,
        "question": "An organization wants to leverage tooling and automation as part of its new DevOps philosophy. Which operational challenge will this resolve?",
        "options": [
            "Repetitive manual tasks that hinder workflows",
            "Time-consuming supervision of creative tasks",
            "Distribution and supply-chain issues",
            "Defective technical equipment that limits innovation",
        ],
        "correct_answer": 0,
    },
    {
        "number": 30,
        "question": "An organization provides a loyalty program for its customers. It recently partnered with other businesses so that customers can get loyalty points at a range of other stores. Why should the organization use application programming interfaces (APIs)?",
        "options": [
            "To migrate all partner data for disaster recovery",
            "To analyze and publish loyalty program statistics to a dashboard",
            "To personalize recommendations for loyalty card users",
            "To connect third-party systems to ensure up-to-date information",
        ],
        "correct_answer": 3,
    },
    {
        "number": 31,
        "question": "An organization wants to add a new function to their application. They want to write the code and let the public cloud provider handle the infrastructure. Which infrastructure solution should they use?",
        "options": [
            "Virtual machines",
            "Bare Metal Solution",
            "Serverless computing",
            "Container Registry",
        ],
        "correct_answer": 2,
    },
    {
        "number": 32,
        "question": "An organization needs a platform to create custom end-to-end artificial intelligence models. Which Google Cloud product or service should the organization use?",
        "options": ["Dataproc", "Compute Engine", "Recommendations AI", "Vertex AI"],
        "correct_answer": 3,
    },
    {
        "number": 33,
        "question": "An organization is looking for a business intelligence solution that allows individual employees and end users to analyze business data and generate insights. Which Google Cloud product or service should the organization use?",
        "options": ["Looker", "Cloud Spanner", "BigQuery", "Dataflow"],
        "correct_answer": 0,
    },
    {
        "number": 34,
        "question": "A food delivery service needs access to real-time menu information from all partner restaurants. They also need to share customer order information with the restaurants in real time. What should the organization use?",
        "options": [
            "Site reliability engineering (SRE)",
            "An application programming interface (API)",
            "A customized machine learning model",
            "A multi-regional database",
        ],
        "correct_answer": 1,
    },
    {
        "number": 35,
        "question": "An organization is migrating their business applications from on-premises to the cloud. How could this impact their operations and personnel costs?",
        "options": [
            "Reduced on-premises infrastructure management costs",
            "Increased on-premises hardware maintenance costs",
            "Reduced cloud software licensing costs",
            "Increased cloud hardware management costs",
        ],
        "correct_answer": 0,
    },
    {
        "number": 36,
        "question": "An organization wants to move to cloud-based collaboration software, but due to limited IT staff one of their main drivers is having low maintenance needs. Which cloud computing model would best suit their requirements?",
        "options": [
            "Platform as a Service (PaaS)",
            "IT as a service (ITaaS)",
            "Infrastructure as a Service (IaaS)",
            "Software as a Service (SaaS)",
        ],
        "correct_answer": 3,
    },
    {
        "number": 37,
        "question": "Which option best describes a benefit of Infrastructure as a Service (IaaS)?",
        "options": [
            "It’s efficient, as IaaS resources are available when needed and resources aren’t wasted by overbuilding capacity.",
            "It has low management overhead, as all administration and management tasks for data, servers, storage, and updates are handled by the cloud vendor.",
            "It's cost-effective, as all infrastructure costs are handled under a single monthly or annual subscription fee.",
            "It reduces development time, as developers can go straight to coding instead of spending time setting up and maintaining a development environment.",
        ],
        "correct_answer": 0,
    },
    {
        "number": 38,
        "question": "In the cloud computing shared responsibility model, what types of content are customers always responsible for, regardless of the computing model chosen?",
        "options": [
            "The customer is responsible for security of the operating system, software stack required to run their applications and any hardware, networks, and physical security.",
            "The customer is responsible for all infrastructure decisions, server configurations and database monitoring.",
            "The customer is responsible for securing anything that they create within the cloud, such as the configurations, access policies, and user data.",
            "The customer is not responsible for any of the data in the cloud, as data management is the responsibility of the cloud provider who is hosting the data.",
        ],
        "correct_answer": 2,
    },
    {
        "number": 39,
        "question": "Which cloud computing service model offers a develop-and-deploy environment to build cloud applications?",
        "options": [
            "Infrastructure as a Service (IaaS)",
            "Function as a Service (FaaS)",
            "Platform as a Service (PaaS)",
            "Software as a Service (SaaS)",
        ],
        "correct_answer": 2,
    },
    {
        "number": 40,
        "question": "What is the benefit of implementing a transformation cloud that is based on open infrastructure?",
        "options": [
            "Open standards make it easier to hire more developers.",
            "On-premises software isn't open source, so cloud applications are more portable.",
            "Open source software makes it easier to patent proprietary software.",
            "Open source software reduces the chance of vendor lock-in.",
        ],
        "correct_answer": 3,
    },
    {
        "number": 41,
        "question": "As the world and business changes, organizations have to decide between embracing new technology and transforming, or keeping their technology and approaches the same. What risks might an organization face by not transforming as their market evolves?",
        "options": [
            "Focusing on ‘how’ they operate can prevent organizations from seeing transformation opportunities.",
            "Organizations risk losing market leadership if they spend too much time on digital transformation.",
            "Focusing on ‘why’ they operate can lead to inefficient use of resources and disruption.",
            "Embracing new technology can cause organizations to overspend on innovation.",
        ],
        "correct_answer": 0,
    },
    {
        "number": 42,
        "question": "Select the definition of digital transformation.",
        "options": [
            "When an organization uses new digital technologies to create or modify financial models for how a business is run.",
            "When an organization uses new digital technologies to create or modify on-premises business processes.",
            "When an organization uses new digital technologies to create or modify business processes, culture, and customer experiences.",
            "When an organization uses new digital technologies to create or modify technology infrastructure to focus on cost saving.",
        ],
        "correct_answer": 2,
    },
    {
        "number": 43,
        "question": "An organization has a new application, and user subscriptions are growing faster than on-premises infrastructure can handle. What benefit of the cloud might help them in this situation?",
        "options": [
            "It's scalable, so the organization could shorten their infrastructure deployment time.",
            "It's cost effective, so the organization will no longer have to pay for computing once the app is in the cloud.",
            "It provides physical access, so the organization can deploy servers faster.",
            "It's secure, so the organization won't have to worry about the new subscribers data.",
        ],
        "correct_answer": 0,
    },
    {
        "number": 44,
        "question": "What is the cloud?",
        "options": [
            "A metaphor for the networking capability of internet providers.",
            "A Google product made up of on-premises IT infrastructure.",
            "A Google product for computing large amounts of data.",
            "A metaphor for a network of data centers.",
        ],
        "correct_answer": 3,
    },
    {
        "number": 45,
        "question": "An organization has made significant investments in their own infrastructure and has regulatory requirements for their data to be hosted on-premises. Which cloud implementation would best suit their needs?",
        "options": [
            "Platform as a service",
            "Software as a service",
            "Private Cloud",
            "Public Cloud",
        ],
        "correct_answer": 2,
    },
    {
        "number": 46,
        "question": "Which item describes a goal of an organization seeking digital transformation?",
        "options": [
            "Break down data silos and generate real time insights.",
            "Ensure better security by decoupling teams and their data.",
            "Streamline their hardware procurement process to forecast at least a quarter into the future.",
            "Reduce emissions by using faster networks in their on-premises workloads.",
        ],
        "correct_answer": 0,
    },
    {
        "number": 47,
        "question": "Select the two capabilities that form the basis of a transformation cloud? Select two correct answers.",
        "options": [
            "Collaboration cloud ensures that the device a user connects with only works on the corporate network.",
            "A trusted cloud gives control of all resources to the user to ensure high availability at all times.",
            "Open infrastructure gives the freedom to innovate by running applications in the place that makes the most sense.",
            "Data cloud provides a unified solution to manage data across the entire data lifecycle.",
            "Sustainable cloud ensures the costs of cloud resources are controlled to prevent budget overrun.",
        ],
        "correct_answer": [2, 3],
        "type": "checkbox",
    },
    {
        "number": 48,
        "question": "What is seen as a limitation of on-premises infrastructure, when compared to cloud infrastructure?",
        "options": [
            "The on-premises hardware procurement process can take a long time.",
            "Scaling processing is too difficult due to power consumption.",
            "The on-premises networking is more complicated.",
            "Maintenance workers do not have physical access to the servers.",
        ],
        "correct_answer": 0,
    },
    {
        "number": 49,
        "question": "In modern application development, which is responsible for the day-to-day management of cloud-based infrastructure, such as patching, upgrades, and monitoring?",
        "options": ["Containers", "Managed services", "Cloud security", "DevOps"],
        "correct_answer": 1,
    },
    {
        "number": 50,
        "question": "What’s the name of Google Cloud’s production-ready platform for running Kubernetes applications across multiple cloud environments?",
        "options": [
            "Container Registry",
            "GKE Enterprise",
            "Knative",
            "Google Kubernetes Engine",
        ],
        "correct_answer": 1,
    },
    {
        "number": 51,
        "question": "What name is given to an environment that comprises some combination of on-premises or private cloud infrastructure and public cloud services?",
        "options": ["Multicloud", "Smart cloud", "Hybrid cloud", "Secure cloud"],
        "correct_answer": 2,
    },
    {
        "number": 52,
        "question": "Which is a fully managed cloud infrastructure solution that lets organizations run their Oracle workloads on dedicated servers in the cloud?",
        "options": [
            "Google Cloud VMware Engine",
            "SQL Server on Google Cloud",
            "Bare metal solution",
            "App Engine",
        ],
        "correct_answer": 2,
    },
    {
        "number": 53,
        "question": "What is one way that organizations can create new revenue streams through APIs?",
        "options": [
            "By developing new products and services internally",
            "By charging developers to access their APIs",
            "By using APIs to track customer shipments",
            "By allowing developers to access their data for free",
        ],
        "correct_answer": 1,
    },
    {
        "number": 54,
        "question": "What term is commonly used to describe a rehost migration strategy for an organization that runs specialized legacy applications that aren’t compatible with cloud-native applications?",
        "options": [
            "Move and improve",
            "Build and deploy",
            "Lift and shift",
            "Install and fall",
        ],
        "correct_answer": 2,
    },
    {
        "number": 55,
        "question": "What is the name of Google Cloud's API management service that can operate APIs with enhanced scale, security, and automation?",
        "options": ["App Engine", "AppSheet", "Apigee", "Cloud API Manager"],
        "correct_answer": 2,
    },
    {
        "number": 56,
        "question": "What name is given to an environment where an organization uses more than one public cloud provider as part of its architecture?",
        "options": ["Multicloud", "Community cloud", "Edge cloud", "Hybrid cloud"],
        "correct_answer": 0,
    },
    {
        "number": 57,
        "question": "What term describes a set of instructions that lets different software programs communicate with each other?",
        "options": [
            "Application programming interface",
            "Network programming interface",
            "Communication link interface",
            "Programming communication link",
        ],
        "correct_answer": 0,
    },
    {
        "number": 58,
        "question": "In modern cloud application development, what name is given to independently deployable, scalable, and maintainable components that can be used to build a wide range of applications?",
        "options": ["Microservices", "Containers", "DevOps", "Monoliths"],
        "correct_answer": 0,
    },
    {
        "number": 59,
        "question": "Which is the responsibility of the cloud provider in a cloud security model?",
        "options": [
            "Managing the customer's user access.",
            "Securing the customer's data.",
            "Maintaining the customer's infrastructure.",
            "Configuring the customer's applications.",
        ],
        "correct_answer": 2,
    },
    {
        "number": 60,
        "question": "Which definition best describes a firewall?",
        "options": [
            "A software program that encrypts data to make it unreadable to unauthorized users",
            "A network security device that monitors and controls incoming and outgoing network traffic based on predefined security rules",
            "A set of security measures designed to protect a computer system or network from cyber attacks",
            "A security model that assumes no user or device can be trusted by default",
        ],
        "correct_answer": 1,
    },
    {
        "number": 61,
        "question": "What common cybersecurity threat involves tricking users into revealing sensitive information or performing actions that compromise security?",
        "options": ["Malware", "Configuration mishap", "Phishing", "Ransomware"],
        "correct_answer": 2,
    },
    {
        "number": 62,
        "question": "Which cybersecurity threat occurs when errors arise during the setup of resources, inadvertently exposing sensitive data and systems to unauthorized access?",
        "options": ["Phishing", "Virus", "Malware", "Configuration mishaps"],
        "correct_answer": 3,
    },
    {
        "number": 63,
        "question": "Which three essential aspects of cloud security form the foundation of the CIA triad?",
        "options": [
            "Compliance, identity, and access management",
            "Containers, infrastructure, and architecture",
            "Confidentiality, integrity, and availability",
            "Certificates, intelligence, and authentication",
        ],
        "correct_answer": 2,
    },
    {
        "number": 64,
        "question": "Which is a benefit of cloud security over traditional on-premises security?",
        "options": [
            "Having physical access to hardware.",
            "Only having to install security updates on a weekly basis.",
            "Large upfront capital investment.",
            "Increased scalability.",
        ],
        "correct_answer": 3,
    },
    {
        "number": 65,
        "question": "Which cloud security principle relates to keeping data accurate and trustworthy?",
        "options": ["Compliance", "Confidentiality", "Integrity", "Control"],
        "correct_answer": 2,
    },
    {
        "number": 66,
        "question": "Which security principle advocates granting users only the access they need to perform their job responsibilities?",
        "options": [
            "Privileged access",
            "Zero-trust architecture",
            "Security by default",
            "Least privilege",
        ],
        "correct_answer": 3,
    },
    {
        "number": 67,
        "question": "Which cybersecurity threat demands a ransom payment from a victim to regain access to their files and systems?",
        "options": ["Spyware", "Trojan", "Ransomware", "Virus"],
        "correct_answer": 2,
    },
    {
        "number": 68,
        "question": "Which cloud security principle ensures that security practices and measures align with established standards and guidelines?",
        "options": ["Confidentiality", "Control", "Compliance", "Integrity"],
        "correct_answer": 2,
    },
    {
        "number": 69,
        "question": "Which report provides a way for Google Cloud to share data about how the policies and actions of governments and corporations affect privacy, security, and access to information?",
        "options": [
            "Compliance reports",
            "Transparency reports",
            "Security reports",
            "Billing reports",
        ],
        "correct_answer": 1,
    },
    {
        "number": 70,
        "question": "Which is one of Google Cloud’s seven trust principles?",
        "options": [
            "Google sells customer data to third parties.",
            "Google Cloud uses customer data for advertising.",
            "We give 'backdoor' access to government entities when requested.",
            "All customer data is encrypted by default.",
        ],
        "correct_answer": 3,
    },
    {
        "number": 71,
        "question": "Which Google Cloud feature allows users to control their data's physical location?",
        "options": ["Areas", "Regions", "Places", "Districts"],
        "correct_answer": 1,
    },
    {
        "number": 72,
        "question": "Which term describes the concept that data is subject to the laws and regulations of the country where it resides?",
        "options": [
            "Data consistency",
            "Data residency",
            "Data sovereignty",
            "Data redundancy",
        ],
        "correct_answer": 2,
    },
    {
        "number": 73,
        "question": "Where can you find details about certifications and compliance standards met by Google Cloud?",
        "options": [
            "Google Cloud console",
            "Marketplace",
            "Compliance resource center",
            "Cloud Storage client libraries",
        ],
        "correct_answer": 2,
    },
]
